// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dczdezufrubtzznvaekc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjemRlenVmcnVidHp6bnZhZWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTkwMTksImV4cCI6MjA1NzUzNTAxOX0.FX51LSfgPRA7tEv9pG81wIIeJonRI7LB3QayYSdqTjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);